# Generated by Django 3.2.4 on 2022-03-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pictures',
            field=models.ImageField(default='0000000', upload_to='pictures'),
        ),
    ]
