# Generated by Django 3.2.4 on 2022-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='pictures',
        ),
    ]
